name: ci
on:
  push:
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Push Docker image to GHCR docker registry
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: gi-yt
          password: ${{ secrets.PUSH_SECRET }}
          registry: ghcr.io
      - name: Build Inventory Image
        run: |
          docker build . --tag ghcr.io/gnulinuxindia/internet-chowkidar:latest -f docker/Dockerfile
          docker push ghcr.io/gnulinuxindia/internet-chowkidar:latest

